name: BurningJudas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9639329218771309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d5e1'
    - '#21201e'
    - '#7995aa'
    - '#496e7e'
    - '#cda99b'
  brandStrength: 0.5
  lightness: 0.2513143583200872
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
